export { escapeHtml, highlightMatch } from "./html"
export { smoothScrollTo, flashAndScroll, persistentHighlight, clearPersistentHighlight } from "./scroll"
export { registerOverlay, unregisterOverlay, isOverlayOpen } from "./overlay"
export { isDesktop, prefersReducedMotion } from "./device"
export { svgToImage } from "./svg"
