name: Feature Request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please read the [Contributing Guidelines](https://github.com/djaffry/mahlzeit-test/blob/main/CONTRIBUTING.md) before submitting.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
      placeholder: I find it frustrating when ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you thought about?
    validations:
      required: false
